### ISSUE TITLE
Auth not working for professionals account

### ISSUE THREAD

**Issue by MichelBaie** [agam778/MS-Office-Electron#3] opened 2021-10-26 08:07 UTC
Hi,
I would like to use office electron, but because i'm using an enterprise account, the login process you seems to use isn't the right.
It gives me an error that my account isn't recognized.

**Comment by agam778** [comment] 2021-10-30 06:13
@MichelBaie Hello?

**Comment by MichelBaie** [comment] 2021-11-05 10:07
Sorry for the wait, https://office.com/?auth=2 seems to work with my enteprise account 😄

**Comment by agam778** [comment] 2021-11-05 13:24
@MichelBaie https://github.com/agam778/MS-Office-Electron/releases/tag/v0.3.5

It's released now, please check if your issue is solved so I can close this comment 😄

**Comment by MichelBaie** [comment] 2021-11-06 17:08
nope, still not working :(

**Comment by agam778** [comment] 2021-11-06 17:09
Welp, it works for me tho
What steps did you do?

**Comment by MichelBaie** [comment] 2021-11-06 17:10
Just installed the app and get to the login page

**Comment by agam778** [comment] 2021-11-06 17:10
Like:
1. First go to the "Applications" menu in the menu bar
2. Click "Use Enterprise version of MS Office"
3. Close the app and open again

worked for me

**Comment by MichelBaie** [comment] 2021-11-06 17:11
Login options have popped up under the form, but my account is still not working

**Comment by agam778** [comment] 2021-11-06 17:11
If you don't mind, can you send a screenshot?

**Comment by MichelBaie** [comment] 2021-11-06 17:11
I'm verifying if it's the right link

**Comment by MichelBaie** [comment] 2021-11-06 17:14
![Sans titre](https://user-images.githubusercontent.com/39345534/140618067-62a3d74f-a2e6-4656-9dfb-770a47abd578.png)

**Comment by MichelBaie** [comment] 2021-11-06 17:14
oops

**Comment by agam778** [comment] 2021-11-06 17:14
Wait a sec, did you close the app and reopen again after selecting the enterprise option in Menu bar?

**Comment by MichelBaie** [comment] 2021-11-06 17:15
nope

**Comment by agam778** [comment] 2021-11-06 17:15
Re-open the app after selecting the enterprise option, then only it will work :)

**Comment by MichelBaie** [comment] 2021-11-06 17:15
works after restarting the app

**Comment by agam778** [comment] 2021-11-06 17:16
Yeah, so the issue is fixed now, right?

**Comment by MichelBaie** [comment] 2021-11-06 17:16
Cool, maybe you should apply without restarting the app ?
I didn't see i had to reload

**Comment by agam778** [comment] 2021-11-06 17:17
Actually, it isnt possible without reopening the app.

I guess i'll add the instructions in the README.md

Can this issue be closed?

**Comment by MichelBaie** [comment] 2021-11-06 17:17
Is it normal if i can't open this excel document ? 
![image](https://user-images.githubusercontent.com/39345534/140618173-c890bb63-98b2-4346-a2cb-02695da623af.png)

**Comment by agam778** [comment] 2021-11-06 17:18
Hmm, maybe that's an issue with your account, cause it works for me

**Comment by MichelBaie** [comment] 2021-11-06 17:19
it works in the browser,i have multiple redirections

**Comment by agam778** [comment] 2021-11-06 17:19
Hmm, try reloading the page (Ctrl+R)

**Comment by MichelBaie** [comment] 2021-11-06 17:19
nothing changes

**Comment by agam778** [comment] 2021-11-06 17:20
Maybe that's an issue with your enterprise account, or electron app

Sorry to say but i can't help with that :(

**Comment by MichelBaie** [comment] 2021-11-06 17:21
do you need informations to debug ?

**Comment by MichelBaie** [comment] 2021-11-06 17:21
is it possible to open f12 menu ?

**Comment by agam778** [comment] 2021-11-06 17:21
Well, yeah if you can

**Comment by MichelBaie** [comment] 2021-11-06 17:22
it isn't working, maybe because of the app in production mode, i'm downloading the repo to launch it in developpment

**Comment by agam778** [comment] 2021-11-06 17:23
Try running the app from the command prompt/terminal, it will surely show an error there

**Comment by MichelBaie** [comment] 2021-11-06 17:23
what's the command ?

**Comment by agam778** [comment] 2021-11-06 17:24
Are you on windows?

**Comment by MichelBaie** [comment] 2021-11-06 17:24
no on pop so

**Comment by MichelBaie** [comment] 2021-11-06 17:24
no errors

**Comment by agam778** [comment] 2021-11-06 17:24
Oh, so basically just go to the terminal
And run `MS-Office-Electron` cause it adds the app in `/usr/bin`

**Comment by MichelBaie** [comment] 2021-11-06 17:25
sure, but it doesn't give me any error when i have the 403 forbidden, let me setup the environement

**Comment by agam778** [comment] 2021-11-06 17:27
Hmm, ok lets see if it works, or it can be the electron's natural behaviour of having some issues with redirects

Well, for me everything works, lemme try once again

**Comment by MichelBaie** [comment] 2021-11-06 17:28
how do you run the app from your repo ?

**Comment by agam778** [comment] 2021-11-06 17:29
1. `yarn`
2. `yarn start`

**Comment by MichelBaie** [comment] 2021-11-06 17:30
it launches the app, do you know how to enable the developper options to be accessible ?
they seems disabled

**Comment by agam778** [comment] 2021-11-06 17:32
Yeah
In `main.js`
![image](https://user-images.githubusercontent.com/68941022/140618590-de3f49a0-5ddb-4c1a-8e3a-be9fae2e566a.png)
make the `devTools` option "true"

and try f12 or "fn+f12"

**Comment by MichelBaie** [comment] 2021-11-06 17:34
doesn't change anything 🤔

**Comment by agam778** [comment] 2021-11-06 17:35
`  {
    label: 'View',
    submenu: [
      { role: 'reload' },
      { role: 'forceReload' },
      { role: 'toggleDevTools' },
      { type: 'separator' },
      { role: 'resetZoom' },
      { role: 'zoomIn' },
      { role: 'zoomOut' },
      { type: 'separator' },
      { role: 'togglefullscreen' }
    ]
  },`
  
  Just replace the old View menu bar code with one i gave above

**Comment by MichelBaie** [comment] 2021-11-06 17:36
woohoo it opens something

**Comment by MichelBaie** [comment] 2021-11-06 17:40
![Sans titre(1)](https://user-images.githubusercontent.com/39345534/140618815-8674bdd5-726b-4719-a3ed-fbe16894ee5d.png)

**Comment by MichelBaie** [comment] 2021-11-06 17:40
maybe there is inter-sites cookies ?

**Comment by agam778** [comment] 2021-11-06 17:42
wait lemme try with a custom user agent then

**Comment by agam778** [comment] 2021-11-06 17:45
Hmm, still doesn't work

**Comment by MichelBaie** [comment] 2021-11-06 17:45
do you have any enterprise account to do tests ?

**Comment by agam778** [comment] 2021-11-06 17:46
Yeah, i just did with my developer account
It shows "403 FORBIDDEN" 😶

**Comment by MichelBaie** [comment] 2021-11-06 17:46
i also use a devlopper account 😄

**Comment by MichelBaie** [comment] 2021-11-06 17:47
Because we pass through sharepoint ?

**Comment by agam778** [comment] 2021-11-06 17:47
Maybe, lemme check the devTools in my browser

**Comment by agam778** [comment] 2021-11-06 17:50
Can't figure out anything right now 🤔

**Comment by MichelBaie** [comment] 2021-11-06 17:50
will you investigate in the future ?

**Comment by agam778** [comment] 2021-11-06 17:51
https://social.technet.microsoft.com/wiki/contents/articles/53250.building-electron-application-to-interact-with-sharepoint-using-oauth-implicit-grant-flow.aspx

Just saw something

**Comment by MichelBaie** [comment] 2021-11-06 17:53
but why does it works in browsers 🤔

**Comment by MichelBaie** [comment] 2021-11-06 17:53
maybe there is a way to bypass those restrictions

**Comment by agam778** [comment] 2021-11-06 17:56
Not really, maybe microsoft can detect if it is using electron base or not, that is why in the guide they are showing to redirect to https://login.microsoftonline.com/common/oauth2/nativeclient and there might be a reason of giving **nativeclient** in the redirection url 😞

**Comment by MichelBaie** [comment] 2021-11-06 17:57
sad, i can't ask to my school to enable things in the azure ad settings :(

**Comment by agam778** [comment] 2021-11-06 17:59
Well, i have a solution
https://github.com/Fmstrat/winapps

Though the repo is little old, it still works without any flaws
little tough to setup but yeah its good 

Even i am using it for some things like some apps which are windows only and adobe etc.

**Comment by MichelBaie** [comment] 2021-11-06 17:59
why not, i have a rdp server running, thanks 😄

**Comment by MichelBaie** [comment] 2021-11-06 18:00
You can close this issue i think

**Comment by agam778** [comment] 2021-11-06 18:00
Windows apps on linux 😄 
![image](https://user-images.githubusercontent.com/68941022/140619302-b916b395-9064-4ca9-a6b7-9f405609e022.png)

**Comment by agam778** [comment] 2021-11-06 18:01
Sure, i'll close the issue
And i might remove the enterprise feature from the app too, because of that azure situation :(

**Closed by agam778** 2021-11-06 18:01 UTC
